// GENERATED by scripts/gen-examples.mjs (npm run generate:examples) -- do not hand-edit.
// The Layout Designer example gallery as one plugin: /examples opens a tabbed tour where every
// card is rendered by the same Carbon code the designer generates for it. /examples.hide closes.
using Carbon.Components;
using Oxide.Game.Rust.Cui;

namespace Carbon.Plugins;

[Info("Layout Designer Examples", "hizen", "1.0.0")]
[Description("Tabbed in-game tour of the Layout Designer examples")]
public class LayoutDesignerExamples : CarbonPlugin
{
    private static readonly string[] Tabs = { "Panel", "Text", "Container", "Button", "Input field", "Countdown", "Image: URL", "Image: Sprite", "Image: Item icon", "Image: Steam avatar", "Image: Image DB", "Outline", "Border", "Draggable & Slot", "Layout: stack", "Repeating list", "Scrolling list", "Showcase: Welcome panel" };

    [ChatCommand("examples")]
    private void ShowCommand(BasePlayer player, string command, string[] args) => Render(player, 0);

    [ChatCommand("examples.hide")]
    private void HideCommand(BasePlayer player, string command, string[] args)
    {
        CuiHelper.DestroyUi(player, "ExamplesRoot");
    }

    [ProtectedCommand("examples.tab")]
    private void TabCommand(ConsoleSystem.Arg arg)
    {
        var player = arg.Player();
        if (player == null) return;
        Render(player, arg.GetInt(0));
    }

    private void Render(BasePlayer player, int tab)
    {
        if (tab < 0 || tab >= Tabs.Length) tab = 0;
        CuiHelper.DestroyUi(player, "ExamplesRoot"); // re-render replaces the previous instance

        using var cui = new CUI(CuiHandler);

        cui.v2.CreateParent(CUI.ClientPanels.Overlay, LuiPosition.Full, "ExamplesRoot")
            .AddCursor();

        // tab bar across the top; the active tab runs no command
        cui.v2.CreatePanel("ExamplesRoot", new LuiPosition(0f, 1f, 1f, 1f), new LuiOffset(0f, -26f, 0f, 0f), "0.05 0.06 0.08 0.97", "ExamplesTabs");
        float tabW = 1f / Tabs.Length;
        for (int i = 0; i < Tabs.Length; i++)
        {
            cui.v2.CreateButton("ExamplesTabs", new LuiPosition(i * tabW, 0f, (i + 1) * tabW, 1f), new LuiOffset(1f, 1f, -1f, -1f),
                i == tab ? "" : $"examples.tab {i}", i == tab ? "0.99 0.35 0.23 1" : "0.12 0.13 0.16 1", true, $"ExTab.{i}");
            cui.v2.CreateText($"ExTab.{i}", LuiPosition.Full, LuiOffset.None, 9, "0.95 0.95 0.97 1", Tabs[i], TextAnchor.MiddleCenter, $"ExTab.{i}.Label");
        }

        // content host the selected example renders into (the demo's stand-in for the usual root)
        cui.v2.CreateEmptyContainer("ExamplesRoot", "ExamplesContent", true)
            .SetAnchorAndOffset(new LuiPosition(0f, 0f, 1f, 1f), new LuiOffset(0f, 0f, 0f, -26f));

        switch (tab)
        {
            case 0: BuildPanel(cui); break;
            case 1: BuildText(cui); break;
            case 2: BuildContainer(cui); break;
            case 3: BuildButton(cui); break;
            case 4: BuildInput(cui); break;
            case 5: BuildCountdown(cui); break;
            case 6: BuildFillUrl(cui); break;
            case 7: BuildFillSprite(cui); break;
            case 8: BuildFillItemicon(cui); break;
            case 9: BuildFillSteamavatar(cui); break;
            case 10: BuildFillImagedb(cui); break;
            case 11: BuildOutline(cui); break;
            case 12: BuildBorder(cui); break;
            case 13: BuildDragSlot(cui); break;
            case 14: BuildLayoutStack(cui); break;
            case 15: BuildRepeatList(cui); break;
            case 16: BuildScrollList(cui); break;
            case 17: BuildShowcaseWelcome(cui); break;
        }

        cui.v2.SendUi(player);
    }

    private void BuildPanel(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "PANEL", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "Solid boxes are the building block — the last one is translucent over a sibling, not the game.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-180f, -55f, -70f, 55f),
            "0.99 0.35 0.23 1", "Solid.A");

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-55f, -55f, 55f, 55f),
            "0.2 0.55 0.85 1", "Solid.B");

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(70f, -55f, 180f, 55f),
            "0.25 0.7 0.45 1", "Solid.C");

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(10f, -75f, 196f, 5f),
            "0.05 0.06 0.08 0.65", "Dimmer");
    }

    private void BuildText(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "TEXT", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "Content, font, size, color and a 3x3 alignment grid.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreateText("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-190f, 32f, 190f, 62f),
            16, "0.95 0.95 0.97 1", "Roboto Condensed — the Rust default", TextAnchor.MiddleLeft, "Font.Regular");

        cui.v2.CreateText("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-190f, 2f, 190f, 32f),
            16, "0.95 0.95 0.97 1", "Roboto Condensed Bold for emphasis", TextAnchor.MiddleLeft, "Font.Bold")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateText("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-190f, -30f, 190f, 2f),
            15, "0.99 0.35 0.23 1", "Permanent Marker for flavor", TextAnchor.MiddleLeft, "Font.Marker")
            .SetTextFont(CUI.Handler.FontTypes.PermanentMarker);

        cui.v2.CreateText("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-190f, -62f, 190f, -30f),
            11, "0.2 0.55 0.85 1", "PRESS START 2P", TextAnchor.MiddleRight, "Font.Pixel")
            .SetTextFont(CUI.Handler.FontTypes.PressStart);
    }

    private void BuildContainer(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "CONTAINER", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "The wrapper has no graphic — select it in the tree and move all four chips at once.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreateEmptyContainer("Card", "ChipGrid", true)
            .SetAnchorAndOffset(LuiPosition.MiddleCenter, new LuiOffset(-90f, -70f, 90f, 60f));

        cui.v2.CreatePanel("ChipGrid",
            new LuiPosition(0f, 0.5f, 0.5f, 1f),
            new LuiOffset(4f, 4f, -4f, -4f),
            "0.99 0.35 0.23 1", "Chip.TL");

        cui.v2.CreatePanel("ChipGrid",
            new LuiPosition(0.5f, 0.5f, 1f, 1f),
            new LuiOffset(4f, 4f, -4f, -4f),
            "0.2 0.55 0.85 1", "Chip.TR");

        cui.v2.CreatePanel("ChipGrid",
            new LuiPosition(0f, 0f, 0.5f, 0.5f),
            new LuiOffset(4f, 4f, -4f, -4f),
            "0.25 0.7 0.45 1", "Chip.BL");

        cui.v2.CreatePanel("ChipGrid",
            new LuiPosition(0.5f, 0f, 1f, 0.5f),
            new LuiOffset(4f, 4f, -4f, -4f),
            "0.12 0.13 0.16 1", "Chip.BR");
    }

    private void BuildButton(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "BUTTON", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "Runs a console command on click; the caption is a child Text. Needs cursor frees the mouse.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreateButton("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-150f, -30f, -10f, 10f),
            "ui.demo confirm", "0.99 0.35 0.23 1", true, "Confirm");

        cui.v2.CreateText("Confirm",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "CONFIRM", TextAnchor.MiddleCenter, "Confirm Label");

        cui.v2.CreateButton("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(10f, -30f, 150f, 10f),
            "ui.demo cancel", "0.12 0.13 0.16 1", true, "Cancel");

        cui.v2.CreateText("Cancel",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "Cancel", TextAnchor.MiddleCenter, "Cancel Label");
    }

    private void BuildInput(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor().AddKeyboard();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "INPUT FIELD", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "Submits typed text to a command. Needs keyboard captures focus; the second field masks input.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-170f, 12f, 170f, 48f),
            "0.05 0.06 0.08 1", "Well.Name");

        cui.v2.CreateInput("Well.Name",
            LuiPosition.Full,
            new LuiOffset(10f, 0f, -10f, 0f),
            "0.95 0.95 0.97 1", "type here...", 14, "ui.demo name", 32, true, CUI.Handler.FontTypes.RobotoCondensedBold, TextAnchor.MiddleLeft, "Input.Name");

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-170f, -40f, 170f, -4f),
            "0.05 0.06 0.08 1", "Well.Pass");

        cui.v2.CreateInput("Well.Pass",
            LuiPosition.Full,
            new LuiOffset(10f, 0f, -10f, 0f),
            "0.95 0.95 0.97 1", "hunter2", 14, "ui.demo pass", 32, true, CUI.Handler.FontTypes.RobotoCondensedBold, TextAnchor.MiddleLeft, "Input.Password").SetInputPassword(true);
    }

    private void BuildCountdown(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "COUNTDOWN", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "A client-side timer — %TIME_LEFT% in the text is replaced as it counts 120 down to 0.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreateCountdown("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-140f, -35f, 140f, 45f),
            42, "0.95 0.95 0.97 1", "%TIME_LEFT%", TextAnchor.MiddleCenter, 120f, 0f, 1f, 1f, null, true, "Timer");
    }

    private void BuildFillUrl(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "IMAGE: URL", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "Any https png/jpg, downloaded by the client at runtime. Panel color is the tint.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreateUrlImage("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-55f, -65f, 55f, 45f),
            "https://raw.githubusercontent.com/CarbonCommunity/Carbon/main/NuGet-ICON.png", "1 1 1 1", "Logo");
    }

    private void BuildFillSprite(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "IMAGE: SPRITE", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "A built-in client sprite by asset path, tinted three ways. Invalid paths can crash the client.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreateSprite("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-180f, -55f, -70f, 55f),
            "assets/content/ui/ui.background.tile.psd", "0.99 0.35 0.23 1", "Sprite.Warm");

        cui.v2.CreateSprite("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-55f, -55f, 55f, 55f),
            "assets/content/ui/ui.background.tile.psd", "0.2 0.55 0.85 1", "Sprite.Cool");

        cui.v2.CreateSprite("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(70f, -55f, 180f, 55f),
            "assets/content/ui/ui.background.tile.psd", "1 1 1 1", "Sprite.Plain");
    }

    private void BuildFillItemicon(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "IMAGE: ITEM ICON", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "An item's inventory icon by item id (+ optional skin id) — here, the Tool Cupboard.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-60f, -70f, 60f, 50f),
            "0.05 0.06 0.08 1", "IconWell");

        cui.v2.CreateItemIcon("IconWell",
            LuiPosition.Full,
            new LuiOffset(10f, 10f, -10f, -10f),
            -97956382, 0, "1 1 1 1", "Icon.TC");
    }

    private void BuildFillSteamavatar(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "IMAGE: STEAM AVATAR", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "A player's avatar by SteamID64 — fetched by the client, no server preload needed.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-58f, -68f, 58f, 48f),
            "0.12 0.13 0.16 1", "AvatarFrame");

        cui.v2.CreateSteamAvatar("AvatarFrame",
            LuiPosition.Full,
            new LuiOffset(4f, 4f, -4f, -4f),
            "76561197960287930", "1 1 1 1", "Avatar");
    }

    private void BuildFillImagedb(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "IMAGE: IMAGE DB", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "A named image preloaded into the image database on plugin load — see the generated lifecycle.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreateImageFromDb("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-55f, -65f, 55f, 45f),
            "carbon_logo", "1 1 1 1", "DbLogo");
    }

    private void BuildOutline(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "OUTLINE", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "A colored duplicate offset behind the graphic — glow on text, drop shadow on panels.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreateText("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-190f, 10f, 190f, 60f),
            26, "0.95 0.95 0.97 1", "OUTLINED HEADLINE", TextAnchor.MiddleCenter, "Glow")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold).SetOutline("0.99 0.35 0.23 1", new Vector2(1.5f, -1.5f));

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-70f, -70f, 70f, -10f),
            "0.2 0.55 0.85 1", "Shadowed").SetOutline("0 0 0 0.9", new Vector2(4f, -4f));
    }

    private void BuildBorder(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "BORDER", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "An inset frame drawn as four edge panels — width and color per panel.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-180f, -60f, -70f, 55f),
            "0.12 0.13 0.16 1", "Framed.Thin");

        cui.v2.CreatePanel("Framed.Thin",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -1f, 0f, 0f),
            "0.55 0.58 0.64 1", "Framed.Thin.border-top");

        cui.v2.CreatePanel("Framed.Thin",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(0f, 0f, 0f, 1f),
            "0.55 0.58 0.64 1", "Framed.Thin.border-bottom");

        cui.v2.CreatePanel("Framed.Thin",
            new LuiPosition(0f, 0f, 0f, 1f),
            new LuiOffset(0f, 1f, 1f, -1f),
            "0.55 0.58 0.64 1", "Framed.Thin.border-left");

        cui.v2.CreatePanel("Framed.Thin",
            new LuiPosition(1f, 0f, 1f, 1f),
            new LuiOffset(-1f, 1f, 0f, -1f),
            "0.55 0.58 0.64 1", "Framed.Thin.border-right");

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-55f, -60f, 55f, 55f),
            "0.12 0.13 0.16 1", "Framed.Accent");

        cui.v2.CreatePanel("Framed.Accent",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -3f, 0f, 0f),
            "0.99 0.35 0.23 1", "Framed.Accent.border-top");

        cui.v2.CreatePanel("Framed.Accent",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(0f, 0f, 0f, 3f),
            "0.99 0.35 0.23 1", "Framed.Accent.border-bottom");

        cui.v2.CreatePanel("Framed.Accent",
            new LuiPosition(0f, 0f, 0f, 1f),
            new LuiOffset(0f, 3f, 3f, -3f),
            "0.99 0.35 0.23 1", "Framed.Accent.border-left");

        cui.v2.CreatePanel("Framed.Accent",
            new LuiPosition(1f, 0f, 1f, 1f),
            new LuiOffset(-3f, 3f, 0f, -3f),
            "0.99 0.35 0.23 1", "Framed.Accent.border-right");

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(70f, -60f, 180f, 55f),
            "0.05 0.06 0.08 1", "Framed.Chunky");

        cui.v2.CreatePanel("Framed.Chunky",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -6f, 0f, 0f),
            "0.2 0.55 0.85 1", "Framed.Chunky.border-top");

        cui.v2.CreatePanel("Framed.Chunky",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(0f, 0f, 0f, 6f),
            "0.2 0.55 0.85 1", "Framed.Chunky.border-bottom");

        cui.v2.CreatePanel("Framed.Chunky",
            new LuiPosition(0f, 0f, 0f, 1f),
            new LuiOffset(0f, 6f, 6f, -6f),
            "0.2 0.55 0.85 1", "Framed.Chunky.border-left");

        cui.v2.CreatePanel("Framed.Chunky",
            new LuiPosition(1f, 0f, 1f, 1f),
            new LuiOffset(-6f, 6f, 0f, -6f),
            "0.2 0.55 0.85 1", "Framed.Chunky.border-right");
    }

    private void BuildDragSlot(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "DRAGGABLE & SLOT", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "Drag the orange chip between the two wells — slots catch draggables with a matching filter.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-170f, -55f, -30f, 45f),
            "0.05 0.06 0.08 1", "Slot.Left").SetSlot("demo.chip");

        cui.v2.CreatePanel("Slot.Left",
            LuiPosition.MiddleCenter,
            new LuiOffset(-40f, -40f, 40f, 40f),
            "0.99 0.35 0.23 1", "Chip").SetDraggable(filter: "demo.chip", dropAnywhere: false);

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(30f, -55f, 170f, 45f),
            "0.05 0.06 0.08 1", "Slot.Right").SetSlot("demo.chip");
    }

    private void BuildLayoutStack(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "LAYOUT: STACK", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "The container arranges its children into slots — reorder in the tree, resize one item to resize all.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreateEmptyContainer("Card", "Menu", true)
            .SetAnchorAndOffset(LuiPosition.MiddleCenter, new LuiOffset(-108f, -76f, 108f, 64f));

        cui.v2.CreateButton("Menu",
            LuiPosition.UpperLeft,
            new LuiOffset(8f, -44f, 208f, -8f),
            "ui.demo play", "0.99 0.35 0.23 1", true, "Play");

        cui.v2.CreateText("Play",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "PLAY", TextAnchor.MiddleCenter, "Play Label");

        cui.v2.CreateButton("Menu",
            LuiPosition.UpperLeft,
            new LuiOffset(8f, -88f, 208f, -52f),
            "ui.demo options", "0.12 0.13 0.16 1", true, "Options");

        cui.v2.CreateText("Options",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "OPTIONS", TextAnchor.MiddleCenter, "Options Label");

        cui.v2.CreateButton("Menu",
            LuiPosition.UpperLeft,
            new LuiOffset(8f, -132f, 208f, -96f),
            "ui.demo quit", "0.12 0.13 0.16 1", true, "Quit");

        cui.v2.CreateText("Quit",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "QUIT", TextAnchor.MiddleCenter, "Quit Label");
    }

    private void BuildRepeatList(CUI cui)
    {
        var Kits = new[]
        {
            new { Title = "Starter", ItemId = -97956382 },
            new { Title = "Builder", ItemId = -2099697608 },
            new { Title = "Lumberjack", ItemId = -151838493 },
        };

        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "REPEATING LIST", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "One editable template (row 0) stamped per row of a list — the ghosts are the other rows.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreateEmptyContainer("Card", "KitList", true)
            .SetAnchorAndOffset(LuiPosition.MiddleCenter, new LuiOffset(-190f, -76f, 190f, 88f));

        for (int i = 0; i < Kits.Length; i++)
        {
            var item = Kits[i];

            cui.v2.CreateButton("KitList",
                LuiPosition.UpperLeft,
                new LuiOffset(8f, -52f - i * 52f, 372f, -8f - i * 52f),
                $"kit.claim {i}", "0.12 0.13 0.16 1", true, $"KitRow.{i}");

            cui.v2.CreateText($"KitRow.{i}",
                LuiPosition.Full,
                LuiOffset.None,
                14, "1 1 1 1", item.Title, TextAnchor.MiddleCenter, $"KitRow Label.{i}");

            cui.v2.CreateItemIcon($"KitRow.{i}",
                LuiPosition.MiddleLeft,
                new LuiOffset(4f, -18f, 40f, 18f),
                item.ItemId, 0, "1 1 1 1", $"KitIcon.{i}");
        }
    }

    private void BuildScrollList(CUI cui)
    {
        var Kits = new[]
        {
            new { Title = "Starter", ItemId = -97956382 },
            new { Title = "Builder", ItemId = -2099697608 },
            new { Title = "Lumberjack", ItemId = -151838493 },
            new { Title = "Scrapper", ItemId = 69511070 },
            new { Title = "Farmer", ItemId = -97956382 },
            new { Title = "Chef", ItemId = -2099697608 },
            new { Title = "Medic", ItemId = -151838493 },
            new { Title = "Raider", ItemId = 69511070 },
        };

        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-220f, -150f, 220f, 150f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "SCROLLING LIST", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "More rows than the box fits — the container is a scroll view sized to its content.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreateScrollView("Card", LuiPosition.MiddleCenter, new LuiOffset(-190f, -76f, 190f, 88f),
            true, false, verticalScrollOptions: new LuiScrollbar { autoHide = true, size = 12 }, name: "KitScroll")
            .SetScrollContent(new LuiPosition(0f, 1f, 1f, 1f), new LuiOffset(0f, -(8f + Kits.Length * 52f), 0f, 0f));

        for (int i = 0; i < Kits.Length; i++)
        {
            var item = Kits[i];

            cui.v2.CreateButton("KitScroll",
                LuiPosition.UpperLeft,
                new LuiOffset(8f, -52f - i * 52f, 372f, -8f - i * 52f),
                $"kit.claim {i}", "0.12 0.13 0.16 1", true, $"KitRow.{i}");

            cui.v2.CreateText($"KitRow.{i}",
                LuiPosition.Full,
                LuiOffset.None,
                14, "1 1 1 1", item.Title, TextAnchor.MiddleCenter, $"KitRow Label.{i}");
        }
    }

    private void BuildShowcaseWelcome(CUI cui)
    {
        cui.v2.CreatePanel("ExamplesContent",
            LuiPosition.MiddleCenter,
            new LuiOffset(-264f, -174f, 264f, 174f),
            "0.08 0.09 0.11 1", "Card").AddCursor();

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -36f, 0f, 0f),
            "0.12 0.13 0.16 1", "TitleStrip");

        cui.v2.CreateText("TitleStrip",
            LuiPosition.Full,
            new LuiOffset(14f, 0f, -42f, 0f),
            15, "0.99 0.35 0.23 1", "SHOWCASE: WELCOME PANEL", TextAnchor.MiddleLeft, "Title")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateButton("TitleStrip",
            LuiPosition.MiddleRight,
            new LuiOffset(-32f, -14f, -4f, 14f),
            "", "0.82 0.24 0.2 1", true, "CloseButton")
            .SetButtonClose("Card");

        cui.v2.CreateText("CloseButton",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "X", TextAnchor.MiddleCenter, "CloseButton Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(14f, 8f, -14f, 26f),
            11, "0.55 0.58 0.64 1", "Everything composed: fills, fonts, buttons, a countdown footer — a template to pick apart.", TextAnchor.MiddleLeft, "Hint");

        cui.v2.CreatePanel("Card",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(12f, -102f, -12f, -44f),
            "0.12 0.13 0.16 1", "Header");

        cui.v2.CreateSteamAvatar("Header",
            LuiPosition.MiddleLeft,
            new LuiOffset(8f, -21f, 50f, 21f),
            "76561197960287930", "1 1 1 1", "HeaderAvatar");

        cui.v2.CreatePanel("HeaderAvatar",
            LuiPosition.Full,
            new LuiOffset(-2f, -2f, 2f, 2f),
            "0 0 0 0", "AvatarRing");

        cui.v2.CreatePanel("AvatarRing",
            new LuiPosition(0f, 1f, 1f, 1f),
            new LuiOffset(0f, -2f, 0f, 0f),
            "0.99 0.35 0.23 1", "AvatarRing.border-top");

        cui.v2.CreatePanel("AvatarRing",
            new LuiPosition(0f, 0f, 1f, 0f),
            new LuiOffset(0f, 0f, 0f, 2f),
            "0.99 0.35 0.23 1", "AvatarRing.border-bottom");

        cui.v2.CreatePanel("AvatarRing",
            new LuiPosition(0f, 0f, 0f, 1f),
            new LuiOffset(0f, 2f, 2f, -2f),
            "0.99 0.35 0.23 1", "AvatarRing.border-left");

        cui.v2.CreatePanel("AvatarRing",
            new LuiPosition(1f, 0f, 1f, 1f),
            new LuiOffset(-2f, 2f, 0f, -2f),
            "0.99 0.35 0.23 1", "AvatarRing.border-right");

        cui.v2.CreateText("Header",
            new LuiPosition(0f, 0.5f, 1f, 1f),
            new LuiOffset(60f, -2f, -10f, 0f),
            16, "0.95 0.95 0.97 1", "Welcome back, survivor", TextAnchor.MiddleLeft, "Welcome")
            .SetTextFont(CUI.Handler.FontTypes.RobotoCondensedBold);

        cui.v2.CreateText("Header",
            new LuiPosition(0f, 0f, 1f, 0.5f),
            new LuiOffset(60f, 2f, -10f, 2f),
            12, "0.55 0.58 0.64 1", "Your daily kit is ready to claim.", TextAnchor.MiddleLeft, "Sub");

        cui.v2.CreatePanel("Card",
            LuiPosition.MiddleCenter,
            new LuiOffset(-248f, -52f, 248f, 26f),
            "0.05 0.06 0.08 1", "KitRow");

        cui.v2.CreateItemIcon("KitRow",
            LuiPosition.MiddleLeft,
            new LuiOffset(10f, -28f, 66f, 28f),
            -97956382, 0, "1 1 1 1", "KitIcon");

        cui.v2.CreateText("KitRow",
            LuiPosition.Full,
            new LuiOffset(76f, 0f, -160f, 0f),
            13, "0.95 0.95 0.97 1", "Starter kit — building plan, tools and a Tool Cupboard.", TextAnchor.MiddleLeft, "KitText");

        cui.v2.CreateButton("KitRow",
            LuiPosition.MiddleRight,
            new LuiOffset(-148f, -20f, -10f, 20f),
            "kit.claim daily", "0.99 0.35 0.23 1", true, "Claim");

        cui.v2.CreateText("Claim",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "CLAIM KIT", TextAnchor.MiddleCenter, "Claim Label");

        cui.v2.CreateText("Card",
            new LuiPosition(0f, 0f, 0.5f, 0f),
            new LuiOffset(14f, 30f, 0f, 48f),
            12, "0.55 0.58 0.64 1", "Next wipe in", TextAnchor.MiddleLeft, "WipeLabel");

        cui.v2.CreateCountdown("Card",
            new LuiPosition(0f, 0f, 0.5f, 0f),
            new LuiOffset(88f, 26f, 240f, 52f),
            18, "0.99 0.35 0.23 1", "%TIME_LEFT%", TextAnchor.MiddleLeft, 3600f, 0f, 1f, 1f, null, true, "WipeTimer");

        cui.v2.CreateButton("Card",
            LuiPosition.LowerRight,
            new LuiOffset(-110f, 26f, -14f, 54f),
            "ui.demo dismiss", "0.12 0.13 0.16 1", true, "Dismiss");

        cui.v2.CreateText("Dismiss",
            LuiPosition.Full,
            LuiOffset.None,
            14, "1 1 1 1", "Dismiss", TextAnchor.MiddleCenter, "Dismiss Label");
    }
}
