// Bundled example layouts for the Layout Designer — one per element / fill / modifier, each a
// self-labeled mini scene. Powers File > Load examples (import these as tabs) and the Help gallery.
// GENERATED by scratchpad gen.mjs from the real element factories — regenerate rather than hand-edit.

import type { LayoutData } from './types'

export interface ExampleLayout {
  id: string
  name: string
  hint: string
  category: 'element' | 'fill' | 'modifier'
  data: LayoutData
  /** Gallery screenshot (in-game render), added once captured. */
  image?: string
}

export const EXAMPLE_LAYOUTS: ExampleLayout[] = [
  {
    "id": "panel",
    "name": "Panel",
    "hint": "A solid colored box — the building block of every UI.",
    "category": "element",
    "data": {
      "elements": [
        {
          "id": "el-1",
          "name": "Backdrop",
          "parentId": null,
          "type": "panel",
          "props": {
            "color": {
              "r": 0.09,
              "g": 0.1,
              "b": 0.12,
              "a": 0.96
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -220,
            "y": -150
          },
          "offsetMax": {
            "x": 220,
            "y": 150
          }
        },
        {
          "id": "el-2",
          "name": "Title",
          "parentId": "el-1",
          "type": "text",
          "anchorMin": {
            "x": 0,
            "y": 1
          },
          "anchorMax": {
            "x": 1,
            "y": 1
          },
          "offsetMin": {
            "x": 12,
            "y": -40
          },
          "offsetMax": {
            "x": -12,
            "y": -8
          },
          "props": {
            "color": {
              "r": 0.99,
              "g": 0.35,
              "b": 0.23,
              "a": 1
            },
            "text": "PANEL",
            "fontSize": 18,
            "align": "MiddleCenter",
            "font": "RobotoCondensedRegular"
          }
        },
        {
          "id": "el-3",
          "name": "Panel.3",
          "parentId": "el-1",
          "type": "panel",
          "props": {
            "color": {
              "r": 0.2,
              "g": 0.55,
              "b": 0.85,
              "a": 1
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -120,
            "y": -70
          },
          "offsetMax": {
            "x": 120,
            "y": 20
          }
        }
      ],
      "canvas": {
        "referenceHeight": 720,
        "aspect": "16:9",
        "rootLayer": "Overlay"
      }
    }
  },
  {
    "id": "text",
    "name": "Text",
    "hint": "A text label.",
    "category": "element",
    "data": {
      "elements": [
        {
          "id": "el-1",
          "name": "Backdrop",
          "parentId": null,
          "type": "panel",
          "props": {
            "color": {
              "r": 0.09,
              "g": 0.1,
              "b": 0.12,
              "a": 0.96
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -220,
            "y": -150
          },
          "offsetMax": {
            "x": 220,
            "y": 150
          }
        },
        {
          "id": "el-2",
          "name": "Title",
          "parentId": "el-1",
          "type": "text",
          "anchorMin": {
            "x": 0,
            "y": 1
          },
          "anchorMax": {
            "x": 1,
            "y": 1
          },
          "offsetMin": {
            "x": 12,
            "y": -40
          },
          "offsetMax": {
            "x": -12,
            "y": -8
          },
          "props": {
            "color": {
              "r": 0.99,
              "g": 0.35,
              "b": 0.23,
              "a": 1
            },
            "text": "TEXT",
            "fontSize": 18,
            "align": "MiddleCenter",
            "font": "RobotoCondensedRegular"
          }
        },
        {
          "id": "el-3",
          "name": "Text.3",
          "parentId": "el-1",
          "type": "text",
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -160,
            "y": -60
          },
          "offsetMax": {
            "x": 160,
            "y": 30
          },
          "props": {
            "color": {
              "r": 0.95,
              "g": 0.95,
              "b": 0.97,
              "a": 1
            },
            "text": "The quick brown fox",
            "fontSize": 22,
            "align": "MiddleCenter",
            "font": "RobotoCondensedRegular"
          }
        }
      ],
      "canvas": {
        "referenceHeight": 720,
        "aspect": "16:9",
        "rootLayer": "Overlay"
      }
    }
  },
  {
    "id": "button",
    "name": "Button",
    "hint": "A clickable button; its label is a child text element.",
    "category": "element",
    "data": {
      "elements": [
        {
          "id": "el-1",
          "name": "Backdrop",
          "parentId": null,
          "type": "panel",
          "props": {
            "color": {
              "r": 0.09,
              "g": 0.1,
              "b": 0.12,
              "a": 0.96
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -220,
            "y": -150
          },
          "offsetMax": {
            "x": 220,
            "y": 150
          }
        },
        {
          "id": "el-2",
          "name": "Title",
          "parentId": "el-1",
          "type": "text",
          "anchorMin": {
            "x": 0,
            "y": 1
          },
          "anchorMax": {
            "x": 1,
            "y": 1
          },
          "offsetMin": {
            "x": 12,
            "y": -40
          },
          "offsetMax": {
            "x": -12,
            "y": -8
          },
          "props": {
            "color": {
              "r": 0.99,
              "g": 0.35,
              "b": 0.23,
              "a": 1
            },
            "text": "BUTTON",
            "fontSize": 18,
            "align": "MiddleCenter",
            "font": "RobotoCondensedRegular"
          }
        },
        {
          "id": "el-3",
          "name": "Button.3",
          "parentId": "el-1",
          "type": "button",
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -90,
            "y": -50
          },
          "offsetMax": {
            "x": 90,
            "y": 10
          },
          "props": {
            "color": {
              "r": 0.2,
              "g": 0.55,
              "b": 0.85,
              "a": 1
            },
            "command": "ui.demo",
            "isProtected": true
          }
        },
        {
          "id": "el-4",
          "name": "Button.3 Label",
          "parentId": "el-3",
          "type": "text",
          "anchorMin": {
            "x": 0,
            "y": 0
          },
          "anchorMax": {
            "x": 1,
            "y": 1
          },
          "offsetMin": {
            "x": 0,
            "y": 0
          },
          "offsetMax": {
            "x": 0,
            "y": 0
          },
          "props": {
            "color": {
              "r": 1,
              "g": 1,
              "b": 1,
              "a": 1
            },
            "text": "Click me",
            "fontSize": 14,
            "align": "MiddleCenter",
            "font": "RobotoCondensedRegular"
          },
          "passthrough": true
        }
      ],
      "canvas": {
        "referenceHeight": 720,
        "aspect": "16:9",
        "rootLayer": "Overlay"
      }
    }
  },
  {
    "id": "input",
    "name": "Input field",
    "hint": "A field the player can type into.",
    "category": "element",
    "data": {
      "elements": [
        {
          "id": "el-1",
          "name": "Backdrop",
          "parentId": null,
          "type": "panel",
          "props": {
            "color": {
              "r": 0.09,
              "g": 0.1,
              "b": 0.12,
              "a": 0.96
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -220,
            "y": -150
          },
          "offsetMax": {
            "x": 220,
            "y": 150
          }
        },
        {
          "id": "el-2",
          "name": "Title",
          "parentId": "el-1",
          "type": "text",
          "anchorMin": {
            "x": 0,
            "y": 1
          },
          "anchorMax": {
            "x": 1,
            "y": 1
          },
          "offsetMin": {
            "x": 12,
            "y": -40
          },
          "offsetMax": {
            "x": -12,
            "y": -8
          },
          "props": {
            "color": {
              "r": 0.99,
              "g": 0.35,
              "b": 0.23,
              "a": 1
            },
            "text": "INPUT FIELD",
            "fontSize": 18,
            "align": "MiddleCenter",
            "font": "RobotoCondensedRegular"
          }
        },
        {
          "id": "el-3",
          "name": "Input.3",
          "parentId": "el-1",
          "type": "input",
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -150,
            "y": -50
          },
          "offsetMax": {
            "x": 150,
            "y": 10
          },
          "props": {
            "color": {
              "r": 1,
              "g": 1,
              "b": 1,
              "a": 1
            },
            "text": "type here...",
            "fontSize": 14,
            "font": "RobotoCondensedBold",
            "align": "MiddleLeft",
            "command": "",
            "charLimit": 0,
            "isProtected": true,
            "password": false
          }
        }
      ],
      "canvas": {
        "referenceHeight": 720,
        "aspect": "16:9",
        "rootLayer": "Overlay"
      }
    }
  },
  {
    "id": "countdown",
    "name": "Countdown",
    "hint": "A client-side countdown timer (%TIME_LEFT%).",
    "category": "element",
    "data": {
      "elements": [
        {
          "id": "el-1",
          "name": "Backdrop",
          "parentId": null,
          "type": "panel",
          "props": {
            "color": {
              "r": 0.09,
              "g": 0.1,
              "b": 0.12,
              "a": 0.96
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -220,
            "y": -150
          },
          "offsetMax": {
            "x": 220,
            "y": 150
          }
        },
        {
          "id": "el-2",
          "name": "Title",
          "parentId": "el-1",
          "type": "text",
          "anchorMin": {
            "x": 0,
            "y": 1
          },
          "anchorMax": {
            "x": 1,
            "y": 1
          },
          "offsetMin": {
            "x": 12,
            "y": -40
          },
          "offsetMax": {
            "x": -12,
            "y": -8
          },
          "props": {
            "color": {
              "r": 0.99,
              "g": 0.35,
              "b": 0.23,
              "a": 1
            },
            "text": "COUNTDOWN",
            "fontSize": 18,
            "align": "MiddleCenter",
            "font": "RobotoCondensedRegular"
          }
        },
        {
          "id": "el-3",
          "name": "Countdown.3",
          "parentId": "el-1",
          "type": "countdown",
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -120,
            "y": -50
          },
          "offsetMax": {
            "x": 120,
            "y": 20
          },
          "props": {
            "color": {
              "r": 1,
              "g": 1,
              "b": 1,
              "a": 1
            },
            "text": "%TIME_LEFT%",
            "fontSize": 18,
            "font": "RobotoCondensedRegular",
            "align": "MiddleCenter",
            "startTime": 60,
            "endTime": 0,
            "step": 1,
            "interval": 1,
            "command": "",
            "isProtected": true
          }
        }
      ],
      "canvas": {
        "referenceHeight": 720,
        "aspect": "16:9",
        "rootLayer": "Overlay"
      }
    }
  },
  {
    "id": "fill-url",
    "name": "Image: URL",
    "hint": "A panel filled with a remote image downloaded at runtime.",
    "category": "fill",
    "data": {
      "elements": [
        {
          "id": "el-1",
          "name": "Backdrop",
          "parentId": null,
          "type": "panel",
          "props": {
            "color": {
              "r": 0.09,
              "g": 0.1,
              "b": 0.12,
              "a": 0.96
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -220,
            "y": -150
          },
          "offsetMax": {
            "x": 220,
            "y": 150
          }
        },
        {
          "id": "el-2",
          "name": "Title",
          "parentId": "el-1",
          "type": "text",
          "anchorMin": {
            "x": 0,
            "y": 1
          },
          "anchorMax": {
            "x": 1,
            "y": 1
          },
          "offsetMin": {
            "x": 12,
            "y": -40
          },
          "offsetMax": {
            "x": -12,
            "y": -8
          },
          "props": {
            "color": {
              "r": 0.99,
              "g": 0.35,
              "b": 0.23,
              "a": 1
            },
            "text": "IMAGE: URL",
            "fontSize": 18,
            "align": "MiddleCenter",
            "font": "RobotoCondensedRegular"
          }
        },
        {
          "id": "el-3",
          "name": "Panel.3",
          "parentId": "el-1",
          "type": "panel",
          "props": {
            "color": {
              "r": 0.95,
              "g": 0.95,
              "b": 0.97,
              "a": 1
            },
            "image": {
              "kind": "url",
              "url": "https://carbonmod.gg/assets/img/logo.png"
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -90,
            "y": -90
          },
          "offsetMax": {
            "x": 90,
            "y": 20
          }
        }
      ],
      "canvas": {
        "referenceHeight": 720,
        "aspect": "16:9",
        "rootLayer": "Overlay"
      }
    }
  },
  {
    "id": "fill-sprite",
    "name": "Image: Sprite",
    "hint": "A panel filled with a built-in Rust client sprite.",
    "category": "fill",
    "data": {
      "elements": [
        {
          "id": "el-1",
          "name": "Backdrop",
          "parentId": null,
          "type": "panel",
          "props": {
            "color": {
              "r": 0.09,
              "g": 0.1,
              "b": 0.12,
              "a": 0.96
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -220,
            "y": -150
          },
          "offsetMax": {
            "x": 220,
            "y": 150
          }
        },
        {
          "id": "el-2",
          "name": "Title",
          "parentId": "el-1",
          "type": "text",
          "anchorMin": {
            "x": 0,
            "y": 1
          },
          "anchorMax": {
            "x": 1,
            "y": 1
          },
          "offsetMin": {
            "x": 12,
            "y": -40
          },
          "offsetMax": {
            "x": -12,
            "y": -8
          },
          "props": {
            "color": {
              "r": 0.99,
              "g": 0.35,
              "b": 0.23,
              "a": 1
            },
            "text": "IMAGE: SPRITE",
            "fontSize": 18,
            "align": "MiddleCenter",
            "font": "RobotoCondensedRegular"
          }
        },
        {
          "id": "el-3",
          "name": "Panel.3",
          "parentId": "el-1",
          "type": "panel",
          "props": {
            "color": {
              "r": 0.95,
              "g": 0.95,
              "b": 0.97,
              "a": 1
            },
            "image": {
              "kind": "sprite",
              "sprite": "assets/icons/gear.png"
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -70,
            "y": -90
          },
          "offsetMax": {
            "x": 70,
            "y": 30
          }
        }
      ],
      "canvas": {
        "referenceHeight": 720,
        "aspect": "16:9",
        "rootLayer": "Overlay"
      }
    }
  },
  {
    "id": "fill-itemicon",
    "name": "Image: Item icon",
    "hint": "A panel showing an item inventory icon (AK-47).",
    "category": "fill",
    "data": {
      "elements": [
        {
          "id": "el-1",
          "name": "Backdrop",
          "parentId": null,
          "type": "panel",
          "props": {
            "color": {
              "r": 0.09,
              "g": 0.1,
              "b": 0.12,
              "a": 0.96
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -220,
            "y": -150
          },
          "offsetMax": {
            "x": 220,
            "y": 150
          }
        },
        {
          "id": "el-2",
          "name": "Title",
          "parentId": "el-1",
          "type": "text",
          "anchorMin": {
            "x": 0,
            "y": 1
          },
          "anchorMax": {
            "x": 1,
            "y": 1
          },
          "offsetMin": {
            "x": 12,
            "y": -40
          },
          "offsetMax": {
            "x": -12,
            "y": -8
          },
          "props": {
            "color": {
              "r": 0.99,
              "g": 0.35,
              "b": 0.23,
              "a": 1
            },
            "text": "IMAGE: ITEM ICON",
            "fontSize": 18,
            "align": "MiddleCenter",
            "font": "RobotoCondensedRegular"
          }
        },
        {
          "id": "el-3",
          "name": "Panel.3",
          "parentId": "el-1",
          "type": "panel",
          "props": {
            "color": {
              "r": 0.95,
              "g": 0.95,
              "b": 0.97,
              "a": 1
            },
            "image": {
              "kind": "itemicon",
              "itemId": 1545779598,
              "skinId": 0
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -70,
            "y": -90
          },
          "offsetMax": {
            "x": 70,
            "y": 30
          }
        }
      ],
      "canvas": {
        "referenceHeight": 720,
        "aspect": "16:9",
        "rootLayer": "Overlay"
      }
    }
  },
  {
    "id": "outline",
    "name": "Outline",
    "hint": "A panel with a colored offset outline modifier.",
    "category": "modifier",
    "data": {
      "elements": [
        {
          "id": "el-1",
          "name": "Backdrop",
          "parentId": null,
          "type": "panel",
          "props": {
            "color": {
              "r": 0.09,
              "g": 0.1,
              "b": 0.12,
              "a": 0.96
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -220,
            "y": -150
          },
          "offsetMax": {
            "x": 220,
            "y": 150
          }
        },
        {
          "id": "el-2",
          "name": "Title",
          "parentId": "el-1",
          "type": "text",
          "anchorMin": {
            "x": 0,
            "y": 1
          },
          "anchorMax": {
            "x": 1,
            "y": 1
          },
          "offsetMin": {
            "x": 12,
            "y": -40
          },
          "offsetMax": {
            "x": -12,
            "y": -8
          },
          "props": {
            "color": {
              "r": 0.99,
              "g": 0.35,
              "b": 0.23,
              "a": 1
            },
            "text": "OUTLINE",
            "fontSize": 18,
            "align": "MiddleCenter",
            "font": "RobotoCondensedRegular"
          }
        },
        {
          "id": "el-3",
          "name": "Panel.3",
          "parentId": "el-1",
          "type": "panel",
          "props": {
            "color": {
              "r": 0.2,
              "g": 0.55,
              "b": 0.85,
              "a": 1
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -110,
            "y": -70
          },
          "offsetMax": {
            "x": 110,
            "y": 20
          },
          "modifiers": {
            "outline": {
              "color": {
                "r": 0,
                "g": 0,
                "b": 0,
                "a": 1
              },
              "distance": {
                "x": 2,
                "y": -2
              }
            }
          }
        }
      ],
      "canvas": {
        "referenceHeight": 720,
        "aspect": "16:9",
        "rootLayer": "Overlay"
      }
    }
  },
  {
    "id": "border",
    "name": "Border",
    "hint": "A panel with an inset border (four edge subpanels).",
    "category": "modifier",
    "data": {
      "elements": [
        {
          "id": "el-1",
          "name": "Backdrop",
          "parentId": null,
          "type": "panel",
          "props": {
            "color": {
              "r": 0.09,
              "g": 0.1,
              "b": 0.12,
              "a": 0.96
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -220,
            "y": -150
          },
          "offsetMax": {
            "x": 220,
            "y": 150
          }
        },
        {
          "id": "el-2",
          "name": "Title",
          "parentId": "el-1",
          "type": "text",
          "anchorMin": {
            "x": 0,
            "y": 1
          },
          "anchorMax": {
            "x": 1,
            "y": 1
          },
          "offsetMin": {
            "x": 12,
            "y": -40
          },
          "offsetMax": {
            "x": -12,
            "y": -8
          },
          "props": {
            "color": {
              "r": 0.99,
              "g": 0.35,
              "b": 0.23,
              "a": 1
            },
            "text": "BORDER",
            "fontSize": 18,
            "align": "MiddleCenter",
            "font": "RobotoCondensedRegular"
          }
        },
        {
          "id": "el-3",
          "name": "Panel.3",
          "parentId": "el-1",
          "type": "panel",
          "props": {
            "color": {
              "r": 0.15,
              "g": 0.16,
              "b": 0.2,
              "a": 1
            },
            "border": {
              "width": 3,
              "color": {
                "r": 0.99,
                "g": 0.35,
                "b": 0.23,
                "a": 1
              }
            }
          },
          "anchorMin": {
            "x": 0.5,
            "y": 0.5
          },
          "anchorMax": {
            "x": 0.5,
            "y": 0.5
          },
          "offsetMin": {
            "x": -110,
            "y": -70
          },
          "offsetMax": {
            "x": 110,
            "y": 20
          }
        }
      ],
      "canvas": {
        "referenceHeight": 720,
        "aspect": "16:9",
        "rootLayer": "Overlay"
      }
    }
  }
]
