name: Generator

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Process
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%\tools
          Generate.bat
          
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Archive
          path: |
            tools\Server\carbon

      - name: ⬆️ FTP Upload Debug
        uses: tomasbkk/action-ftp-upload@v1.0
        if: ${{ inputs.debug }}
        with:
          user: redist@carbonmod.gg
          password: ${{ secrets.FTP_PWD }}
          host: 147.135.88.204
          src: "tools/Server/carbon/results/*"
          dest: "metadata"
