name: Generator

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Process
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%\tools
          Generate.bat
          
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Archive
          path: |
            tools\Server\carbon

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp://147.135.88.204
          username: redist@carbonmod.gg
          password: ${{ secrets.FTP_PWD }}
          local-dir: tools/Server/carbon/results
          server-dir: /metadata/

